import { Inter } from "next/font/google";
import Footer from "./_components/footer";
import "./globals.css";
import RootLayoutClient from "./RootLayoutClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eat Swift",
  description: "Generated by webcraftco",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootLayoutClient>
          {children}
        </RootLayoutClient>
        <Footer />
      </body>
    </html>
  );
}
